language: ruby
cache: bundler
rvm:
  - 2.5.1
  - 2.6.5
addons:
  code_climate:
    repo_token: 3a5842d3d6c393759eaf9ea134c751c07371cd4f185d446ffe82fe116414972d
before_install:
  - yes | gem update --system
